# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 21, 13, 52, 30, 534065), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 21, 13, 52, 30, 534065), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 21, 13, 52, 30, 534065), verbose_name='Дата'),
        ),
    ]
